[이분탐색] 5월 17일
Altu-Bitu-6/Altu-Bitu_YuHyoju pull request #10
Opened 2024-05-07 09:50 UTC by oohyj

### 인적사항
학번 : 2076272
이름 : 유효주

### 과제제출
기존 제출: 10815 , 16401
추가 제출:

2024-05-09 16:39 UTC, hanby-choi requested changes
**[이분탐색 이론 코드 리뷰 완료]**
10815, 16401 코드리뷰 완료

안녕하세요, 효주님! 이분탐색 과제 문제들을 열심히 풀어주셨네요👍🏻 다만 16401번을 이분 탐색이 아니라 선형 탐색으로 접근하셔서 백준에 제출 시 시간 초과가 나는 것 같습니다. 이분 탐색으로 푸는 방법을 고민해보시고 다시 제출해주시면 감사하겠습니다! 이번주도 고생하셨습니다~

2024-05-09 16:39 UTC, hanby-choi commented on 10_이분탐색/필수/10815.cpp
> +int binarySearch( int n  , int input , vector<int> &arr){
이분 탐색을 사용해 특정 숫자의 존재 유무를 구하는 함수를 잘 구현해 주셨네요!

2024-05-09 16:39 UTC, hanby-choi commented on 10_이분탐색/필수/16401.cpp
> +                   max = max-1; //max 값을 1씩 줄이기
P1: 현재 적어주신 로직은 O(log n)의 이분 탐색이 아니라 O(n)의 선형 탐색을 하고 있네요! 이 때문에 현재 백준에 제출했을 때 시간 초과가 나므로, 이분 탐색으로 푸는 방법을 고민해보시면 좋을 것 같습니다. 감이 오지 않으신다면 모범 답안을 참고하셔서 추가 제출 부탁드립니다!

2024-05-10 09:10 UTC, oohyj commented on 10_이분탐색/필수/16401.cpp
> +                   max = max-1; //max 값을 1씩 줄이기
제출한 것 수정했습니다. 시간이 없어 확인하지 못했는데 감사합니다! @hanby-choi

2024-05-10 13:05 UTC, hanby-choi commented on 10_이분탐색/필수/16401.cpp
> +                   max = max-1; //max 값을 1씩 줄이기
16401번 추가 제출 올려주신 것 확인했습니다! 수고하셨습니다😊

2024-05-10 13:06 UTC, hanby-choi approved these changes

2024-05-11 15:30 UTC, merged

2024-06-04 10:00 UTC, hajungIm reviewed
[이분탐색 (구현) 코드 리뷰 완료]
 **17266** 코드 리뷰 완료.
효주님 안녕하세요!
코드 리뷰가 늦어져서 죄송합니다🥲
코드 구현 잘 하셨습니다!!! 잘봤습니당☺️
주석으로 꼼꼼하게 학습하신 점 너무 인상 깊었어요❣️👏🏻👏🏻👏🏻
궁금한 점이 있으면 리뷰어를 호출해주세요!

 고생하셨습니다🤍

2024-06-04 10:00 UTC, hajungIm commented on 10_이분탐색/필수/17266.cpp
주석으로 꼼꼼하게 공부해주시고, 넘넘 잘 이해하신것 같습니다!!💖👍🏻👍🏻👍🏻
이분 탐색에서는 `while(start <= end)`와
문제의 조건을 만족하는지 확인하는 함수 `check`를 구현하면 다 풀린다는점!
이분 탐색을 적용하고 싶을 때 한 번 떠올려주세용🥰