03 정수론
Altu-Bitu-6/Altu-Bitu_YuHyoju pull request #3
Opened 2024-03-05 08:56 UTC by oohyj

인적사항
학번: 2076272
이름: 유효주

과제제출
기존제출: 1735,6588
추가제출:

2024-03-08 06:28 UTC, chae-jpg approved these changes
**[정수론 이론 코드리뷰 완료]**

1735(P1), 6588(P3)
효주님 안녕하세요! 코드 리뷰 완료되었습니다👍
현재 1735번 문제에서 오답 판정이 나오고 있습니다 😢 
리뷰 확인해주시고 수정하신 후 다시 리뷰어 호출 부탁드립니다!
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-03-08 06:28 UTC, chae-jpg commented on 03_정수론/필수/1735.cpp
> +            gcd = i;
유클리드 호제법을 잘 구현해주셨어요!

2024-03-08 06:28 UTC, chae-jpg commented on 03_정수론/필수/1735.cpp
> +    cout << sum << " "<< lcd << "\n";
P1
현재 이 부분의 출력으로 인해 백준 상으로 오답 판정이 나오고 있습니다!
sum과 lcd 각각도 공약수가 존재할 수 있어요! 이 때 발생하는 문제를 어떻게 해결하면 좋을까요?

2024-03-08 06:28 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +vector<bool> findPrime(int n){
에라토스테네스의 체를 이용해서 소수를 잘 판정해주셨네요!

2024-03-08 06:28 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +void findBigOne(vector<bool> is_prime){
함수 분리 좋아요!
주석도 이해하기 너무 좋네요 👍

2024-03-08 06:28 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +    }
합이 두 소수로 이루어진 경우를 구해둔 소수 여부 배열을 이용해서 잘 찾아주셨어요!

2024-03-08 06:28 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +            cout << rest + i << " = " << i <<" + "<< rest <<"\n";
P3
알튜비튜에서는 실수를 막기 위해 입출력은 메인 함수에서만 하도록 권장하고 있습니다!
string을 메인에 리턴하고, 그 결과를 메인에서 출력하는 식으로 변경하면 더 좋을 것 같아요~

2024-03-08 06:28 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +        else input.push_back(n);
n==0일 시 break되기 때문에 else는 굳이  붙이지 않아도 됩니다!

2024-03-08 07:21 UTC, kimhj010502 approved these changes
**[정수론 구현 문제 코드 리뷰 완료]**

효주님 안녕하세요!
과제하시느라 수고 많으셨습니다!! 
궁금한 점이 있으면 리뷰어를 호출해주세요!

2024-03-10 13:34 UTC, chae-jpg requested changes
안녕하세요 효주님! 코드에서 수정 필요한 부분이 있어 다시 코멘트 드립니다 😢 
리뷰 확인 후 수정하신 뒤, 다시 리뷰어를 호출해주세요!

2024-03-10 13:44 UTC, oohyj commented on 03_정수론/필수/1735.cpp
> +    cout << sum << " "<< lcd << "\n";
수정했습니다. 늦어서 죄송합니다!

2024-03-11 05:58 UTC, oohyj commented
@chae-jpg 혹시 머지해도 될까요?

2024-03-13 02:40 UTC, chae-jpg approved these changes
**[정수론 이론 코드리뷰 완료]**

안녕하세요 효주님! 코드 수정 확인되었습니다. 머지하셔도 좋습니다~ 수고하셨습니다!

2024-03-13 06:49 UTC, merged